preference_pairs_file: /home/ran.ding/messy-kitchen/dso/messy_kitchen_data/dpo_data/messy_kitchen_configs/dpo_preference_pairs.json
max_samples: 2
checkpoint_path: /home/ran.ding/messy-kitchen/dso/submodules/partcrafter_ran/runs/messy_kitchen/part_1/messy_kitchen_part1_mp8_nt512/checkpoints/017000
use_lora: true
lora_r: 8
lora_alpha: 16
lora_dropout: 0.1
batch_size: 1
learning_rate: 0.0001
scale_lr: false
lr_warmup_steps: 2
use_adafactor: false
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1.0e-08
max_train_steps: 3
max_grad_norm: 1.0
gradient_accumulation_steps: 1
flow_matching_t_logit_normal_mu: 0.0
flow_matching_t_logit_normal_sigma: 1.0
dpo_beta: 0.1
sample_same_epsilon: true
log_interval: 1
save_interval: 10
ckpt_interval: 10
seed: 42
output_dir: ./test_outputs
exp_name: minimal_dpo_test
logger_type: tensorboard
resume_from_checkpoint: null
